FROM alpine:latest
MAINTAINER      manasashetty
RUN apk update && curl && ttf-dejavu && openjdk8
WORKDIR /usr/local/tomcat
RUN curl -O https://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.50/bin/apache-tomcat-8.5.50.tar.gz
RUN tar xvfz apache*.tar.gz
RUN mv apache-tomcat-8.5.50/* /usr/local/tomcat
EXPOSE 8080
CMD /usr/local/tomcat/bin/catalina.sh run